services:
  app:
    build: .
    image: kvdb-image
    container_name: kvdb-container
    ports:
      - "3002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    restart: always

  db:
    image: postgres:16
    container_name: kvdb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
